
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OR_OP = 12;
  public static final int PARENTH2 = 9;
  public static final int INDEPENDENCE = 52;
  public static final int PARENTH1 = 8;
  public static final int AND_OP = 11;
  public static final int DARE = 49;
  public static final int GROUP = 24;
  public static final int STRING_WORD = 21;
  public static final int SEMICOLON_SIGN = 5;
  public static final int NODE = 29;
  public static final int STRESS = 58;
  public static final int DECLARE = 2;
  public static final int APPREHESION = 46;
  public static final int ABSTRACTION = 44;
  public static final int SELFSUFFICIENCY = 54;
  public static final int LOOP = 35;
  public static final int FALSE = 38;
  public static final int NOT = 10;
  public static final int ASSIG_OP = 7;
  public static final int MIN = 28;
  public static final int NOT_EQUAL_OP = 16;
  public static final int GETSIMILITUDE = 42;
  public static final int PRINTGRAPH = 41;
  public static final int NUM = 71;
  public static final int LIVELINESS = 63;
  public static final int CURLY_BR2 = 4;
  public static final int CURLY_BR1 = 3;
  public static final int PRINTLN = 62;
  public static final int BOOLEAN_WORD = 23;
  public static final int AFFABILITY = 45;
  public static final int GREATER_EQUAL_OP = 14;
  public static final int TRUE = 37;
  public static final int LESS_OP = 17;
  public static final int INT_WORD = 22;
  public static final int ERRORLEX = 68;
  public static final int EQUAL_OP = 13;
  public static final int MAX = 27;
  public static final int ELSE = 34;
  public static final int BRACKET2 = 32;
  public static final int CARETOSTANDARDS = 48;
  public static final int BRACKET1 = 31;
  public static final int PRIVACY = 66;
  public static final int STABILITY = 57;
  public static final int GREATER_OP = 18;
  public static final int SOCIABILITY = 56;
  public static final int GETFEATURES = 43;
  public static final int EOF = 0;
  public static final int LESS_EQUAL_OP = 15;
  public static final int READFEATVAL = 36;
  public static final int FEATURES = 30;
  public static final int SELFCONTROL = 53;
  public static final int POINT_SIGN = 60;
  public static final int ANXIETY = 47;
  public static final int MAIN = 6;
  public static final int SENSITIVITY = 55;
  public static final int DOMINANCE = 50;
  public static final int error = 1;
  public static final int GENERATEGROUP = 40;
  public static final int SURVEILLANCE = 59;
  public static final int IF = 33;
  public static final int ID = 69;
  public static final int READSTRING = 39;
  public static final int OPENNESSTOCHANGE = 64;
  public static final int COMMA_SIGN = 26;
  public static final int REASONING = 67;
  public static final int NEW = 25;
  public static final int ARRAYSTRING = 61;
  public static final int STRING = 70;
  public static final int ADD_OP = 19;
  public static final int HARDNESS = 51;
  public static final int SUBS_OP = 20;
  public static final int PERFECTIONISM = 65;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DECLARE",
  "CURLY_BR1",
  "CURLY_BR2",
  "SEMICOLON_SIGN",
  "MAIN",
  "ASSIG_OP",
  "PARENTH1",
  "PARENTH2",
  "NOT",
  "AND_OP",
  "OR_OP",
  "EQUAL_OP",
  "GREATER_EQUAL_OP",
  "LESS_EQUAL_OP",
  "NOT_EQUAL_OP",
  "LESS_OP",
  "GREATER_OP",
  "ADD_OP",
  "SUBS_OP",
  "STRING_WORD",
  "INT_WORD",
  "BOOLEAN_WORD",
  "GROUP",
  "NEW",
  "COMMA_SIGN",
  "MAX",
  "MIN",
  "NODE",
  "FEATURES",
  "BRACKET1",
  "BRACKET2",
  "IF",
  "ELSE",
  "LOOP",
  "READFEATVAL",
  "TRUE",
  "FALSE",
  "READSTRING",
  "GENERATEGROUP",
  "PRINTGRAPH",
  "GETSIMILITUDE",
  "GETFEATURES",
  "ABSTRACTION",
  "AFFABILITY",
  "APPREHESION",
  "ANXIETY",
  "CARETOSTANDARDS",
  "DARE",
  "DOMINANCE",
  "HARDNESS",
  "INDEPENDENCE",
  "SELFCONTROL",
  "SELFSUFFICIENCY",
  "SENSITIVITY",
  "SOCIABILITY",
  "STABILITY",
  "STRESS",
  "SURVEILLANCE",
  "POINT_SIGN",
  "ARRAYSTRING",
  "PRINTLN",
  "LIVELINESS",
  "OPENNESSTOCHANGE",
  "PERFECTIONISM",
  "PRIVACY",
  "REASONING",
  "ERRORLEX",
  "ID",
  "STRING",
  "NUM"
  };
}

